const { classifyInputForClient } = require('./index');

const clientData = [
    { title: 'Java Developer', label: 'Good Fit' },
    { title: 'Cook', label: 'Irrelevant' },
    { title: 'ML Engineer', label: 'Good Fit' },
    { title: 'Full Stack Engineer', label: 'Good Fit' },
    { title: 'Graphic Designer', label: 'Irrelevant' },
    { title: 'Data Scientist', label: 'Good Fit' },
    { title: 'Project Manager', label: 'Irrelevant' },
    { title: 'DevOps Engineer', label: 'Good Fit' },
    { title: 'Accountant', label: 'Irrelevant' },
    { title: 'System Administrator', label: 'Good Fit' },
    { title: 'HR Specialist', label: 'Irrelevant' },
    { title: 'Frontend Developer', label: 'Good Fit' },
    { title: 'Sales Manager', label: 'Irrelevant' },
    { title: 'Backend Developer', label: 'Good Fit' },
    { title: 'Customer Service Representative', label: 'Irrelevant' },
    { title: 'Mobile App Developer', label: 'Good Fit' },
    { title: 'Content Writer', label: 'Irrelevant' },
    { title: 'Network Engineer', label: 'Good Fit' },
    { title: 'Marketing Coordinator', label: 'Irrelevant' },
    { title: 'QA Tester', label: 'Good Fit' },
    { title: 'Business Analyst', label: 'Irrelevant' },
    { title: 'Cloud Solutions Architect', label: 'Good Fit' },
    { title: 'Recruiter', label: 'Irrelevant' },
    { title: 'Cybersecurity Specialist', label: 'Good Fit' },
    { title: 'Event Planner', label: 'Irrelevant' },
    { title: 'AI Researcher', label: 'Good Fit' },
    { title: 'Legal Advisor', label: 'Irrelevant' },
    { title: 'Database Administrator', label: 'Good Fit' },
    { title: 'Office Manager', label: 'Irrelevant' },
    { title: 'Embedded Systems Engineer', label: 'Good Fit' },
    { title: 'Public Relations Specialist', label: 'Irrelevant' },
    { title: 'IT Support Technician', label: 'Good Fit' },
    { title: 'Graphic Illustrator', label: 'Irrelevant' },
    { title: 'Software Architect', label: 'Good Fit' },
    { title: 'Operations Manager', label: 'Irrelevant' },
    { title: 'Big Data Engineer', label: 'Good Fit' },
    { title: 'Procurement Specialist', label: 'Irrelevant' },
    { title: 'Technical Writer', label: 'Good Fit' },
    { title: 'Logistics Coordinator', label: 'Irrelevant' },
    { title: 'Blockchain Developer', label: 'Good Fit' },
    { title: 'Social Media Manager', label: 'Irrelevant' },
    { title: 'Robotics Engineer', label: 'Good Fit' },
    { title: 'Nutritionist', label: 'Irrelevant' },
    { title: 'Computer Vision Engineer', label: 'Good Fit' },
    { title: 'Fashion Designer', label: 'Irrelevant' },
    { title: 'IT Consultant', label: 'Good Fit' },
    { title: 'Real Estate Agent', label: 'Irrelevant' },
    { title: 'Firmware Engineer', label: 'Good Fit' },
    { title: 'Translator', label: 'Irrelevant' },
    { title: 'Augmented Reality Developer', label: 'Good Fit' },
    { title: 'Therapist', label: 'Irrelevant' },
    { title: 'Game Developer', label: 'Good Fit' },
    { title: 'Bartender', label: 'Irrelevant' },
    { title: 'Bioinformatics Scientist', label: 'Good Fit' },
    { title: 'Electrician', label: 'Irrelevant' },
    { title: 'Virtual Reality Engineer', label: 'Good Fit' },
    { title: 'Waiter', label: 'Irrelevant' },
    { title: 'SEO Specialist', label: 'Good Fit' },
    { title: 'Janitor', label: 'Irrelevant' },
    { title: 'Natural Language Processing Engineer', label: 'Good Fit' },
    { title: 'Personal Trainer', label: 'Irrelevant' },
    { title: 'IT Project Coordinator', label: 'Good Fit' },
    { title: 'Photographer', label: 'Irrelevant' },
    { title: 'Data Engineer', label: 'Good Fit' },
    { title: 'Chef', label: 'Irrelevant' },
    { title: 'Software Tester', label: 'Good Fit' },
    { title: 'Nurse', label: 'Irrelevant' },
    { title: 'Information Security Analyst', label: 'Good Fit' },
    { title: 'Barista', label: 'Irrelevant' },
    { title: 'UX/UI Designer', label: 'Good Fit' },
    { title: 'Receptionist', label: 'Irrelevant' },
    { title: 'Technical Support Engineer', label: 'Good Fit' },
    { title: 'Hairdresser', label: 'Irrelevant' },
    { title: 'Bioengineer', label: 'Good Fit' },
    { title: 'Driver', label: 'Irrelevant' },
    { title: 'Software Development Manager', label: 'Good Fit' },
    { title: 'Librarian', label: 'Irrelevant' },
    { title: 'Cloud Engineer', label: 'Good Fit' },
    { title: 'Security Guard', label: 'Irrelevant' },
    { title: 'Data Analyst', label: 'Good Fit' },
    { title: 'Gardener', label: 'Irrelevant' },
    { title: 'Mobile Developer', label: 'Good Fit' },
    { title: 'Sales Associate', label: 'Irrelevant' },
    { title: 'AI Engineer', label: 'Good Fit' },
    { title: 'Flight Attendant', label: 'Irrelevant' },
    { title: 'Technical Recruiter', label: 'Good Fit' },
    { title: 'Receptionist', label: 'Irrelevant' },
    { title: 'Software Engineer', label: 'Good Fit' },
    { title: 'Cashier', label: 'Irrelevant' },
    { title: 'Network Architect', label: 'Good Fit' },
    { title: 'Painter', label: 'Irrelevant' },
    { title: 'Site Reliability Engineer', label: 'Good Fit' },
    { title: 'Tutor', label: 'Irrelevant' },
    { title: 'Data Architect', label: 'Good Fit' },
    { title: 'Mechanic', label: 'Irrelevant' },
    { title: 'Machine Learning Specialist', label: 'Good Fit' },
    { title: 'Bartender', label: 'Irrelevant' },
    { title: 'DevSecOps Engineer', label: 'Good Fit' },
    { title: 'Cashier', label: 'Irrelevant' },
    { title: 'SRE Engineer', label: 'Good Fit' },
    { title: 'Florist', label: 'Irrelevant' },
    { title: 'Software Development Engineer in Test', label: 'Good Fit' },
    { title: 'Waiter', label: 'Irrelevant' },
    { title: 'Full Stack Developer', label: 'Good Fit' },
    { title: 'Barista', label: 'Irrelevant' },
    { title: 'Information Technology Manager', label: 'Good Fit' },
    { title: 'Chef', label: 'Irrelevant' },
    { title: 'Data Visualization Specialist', label: 'Good Fit' },
    { title: 'Security Officer', label: 'Irrelevant' },
    { title: 'Backend Engineer', label: 'Good Fit' },
    { title: 'Housekeeper', label: 'Irrelevant' },
    { title: 'Frontend Engineer', label: 'Good Fit' },
    { title: 'Delivery Driver', label: 'Irrelevant' },
    { title: 'Cloud Solutions Developer', label: 'Good Fit' },
    { title: 'Waitress', label: 'Irrelevant' },
    { title: 'Software Development Intern', label: 'Good Fit' },
    { title: 'Retail Associate', label: 'Irrelevant' },
    { title: 'AI Developer', label: 'Good Fit' },
    { title: 'Parking Attendant', label: 'Irrelevant' },
    { title: 'Solutions Architect', label: 'Good Fit' },
    { title: 'Construction Worker', label: 'Irrelevant' },
    { title: 'Technical Account Manager', label: 'Good Fit' },
    { title: 'Massage Therapist', label: 'Irrelevant' },
    { title: 'AI Specialist', label: 'Good Fit' },
    { title: 'Receptionist', label: 'Irrelevant' },
    { title: 'Backend Systems Developer', label: 'Good Fit' },
    { title: 'Barber', label: 'Irrelevant' },
    { title: 'Machine Learning Engineer', label: 'Good Fit' },
    { title: 'Waitstaff', label: 'Irrelevant' },
    { title: 'Data Operations Analyst', label: 'Good Fit' },
    { title: 'Housekeeper', label: 'Irrelevant' },
    { title: 'Software Quality Assurance Engineer', label: 'Good Fit' },
    { title: 'Customer Service Agent', label: 'Irrelevant' },
    { title: 'Frontend Web Developer', label: 'Good Fit' },
    { title: 'Cashier', label: 'Irrelevant' },
    { title: 'AI Architect', label: 'Good Fit' },
    { title: 'Server', label: 'Irrelevant' },
    { title: 'Data Science Manager', label: 'Good Fit' },
    { title: 'Retail Manager', label: 'Irrelevant' },
    { title: 'Backend Developer', label: 'Good Fit' },
    { title: 'Cleaner', label: 'Irrelevant' },
    { title: 'Full Stack Software Engineer', label: 'Good Fit' },
    { title: 'Waiter', label: 'Irrelevant' },
    { title: 'DevOps Specialist', label: 'Good Fit' },
    { title: 'Hostess', label: 'Irrelevant' },
    { title: 'Data Mining Engineer', label: 'Good Fit' },
    { title: 'Busser', label: 'Irrelevant' },
    { title: 'Cloud Infrastructure Engineer', label: 'Good Fit' },
    { title: 'Dishwasher', label: 'Irrelevant' },
    { title: 'Software Development Lead', label: 'Good Fit' },
    { title: 'Barista', label: 'Irrelevant' },
    { title: 'AI Systems Engineer', label: 'Good Fit' },
    { title: 'Host', label: 'Irrelevant' },
    { title: 'Backend API Developer', label: 'Good Fit' },
    { title: 'Concierge', label: 'Irrelevant' },
    { title: 'Software Solutions Engineer', label: 'Good Fit' },
    { title: 'Waitress', label: 'Irrelevant' },
    { title: 'Java Developer', label: 'Good Fit' },
    { title: 'Cook', label: 'Irrelevant' },
    { title: 'ML Engineer', label: 'Good Fit' },
    { title: 'Full Stack Engineer', label: 'Good Fit' },
    { title: 'Graphic Designer', label: 'Irrelevant' },
    { title: 'Data Scientist', label: 'Good Fit' },
    { title: 'Project Manager', label: 'Irrelevant' },
    { title: 'DevOps Engineer', label: 'Good Fit' },
    { title: 'Accountant', label: 'Irrelevant' },
    { title: 'System Administrator', label: 'Good Fit' },
    { title: 'HR Specialist', label: 'Irrelevant' },
    { title: 'Frontend Developer', label: 'Good Fit' },
    { title: 'Sales Manager', label: 'Irrelevant' },
    { title: 'Backend Developer', label: 'Good Fit' },
    { title: 'Customer Service Representative', label: 'Irrelevant' },
    { title: 'Mobile App Developer', label: 'Good Fit' },
    { title: 'Content Writer', label: 'Irrelevant' },
    { title: 'Network Engineer', label: 'Good Fit' },
    { title: 'Marketing Coordinator', label: 'Irrelevant' },
    { title: 'QA Tester', label: 'Good Fit' },
    { title: 'Business Analyst', label: 'Irrelevant' },
    { title: 'Cloud Solutions Architect', label: 'Good Fit' },
    { title: 'Recruiter', label: 'Irrelevant' },
    { title: 'Cybersecurity Specialist', label: 'Good Fit' },
    { title: 'Event Planner', label: 'Irrelevant' },
    { title: 'AI Researcher', label: 'Good Fit' },
    { title: 'Legal Advisor', label: 'Irrelevant' },
    { title: 'Database Administrator', label: 'Good Fit' },
    { title: 'Office Manager', label: 'Irrelevant' },
    { title: 'Embedded Systems Engineer', label: 'Good Fit' },
    { title: 'Public Relations Specialist', label: 'Irrelevant' },
    { title: 'IT Support Technician', label: 'Good Fit' },
    { title: 'Graphic Illustrator', label: 'Irrelevant' },
    { title: 'Software Architect', label: 'Good Fit' },
    { title: 'Operations Manager', label: 'Irrelevant' },
    { title: 'Big Data Engineer', label: 'Good Fit' },
    { title: 'Procurement Specialist', label: 'Irrelevant' },
    { title: 'Technical Writer', label: 'Good Fit' },
    { title: 'Logistics Coordinator', label: 'Irrelevant' },
    { title: 'Blockchain Developer', label: 'Good Fit' },
    { title: 'Social Media Manager', label: 'Irrelevant' },
    { title: 'Robotics Engineer', label: 'Good Fit' },
    { title: 'Nutritionist', label: 'Irrelevant' },
    { title: 'Computer Vision Engineer', label: 'Good Fit' },
    { title: 'Fashion Designer', label: 'Irrelevant' },
    { title: 'IT Consultant', label: 'Good Fit' },
    { title: 'Real Estate Agent', label: 'Irrelevant' },
    { title: 'Firmware Engineer', label: 'Good Fit' },
    { title: 'Translator', label: 'Irrelevant' },
    { title: 'Augmented Reality Developer', label: 'Good Fit' },
    { title: 'Therapist', label: 'Irrelevant' },
    { title: 'Game Developer', label: 'Good Fit' },
    { title: 'Bartender', label: 'Irrelevant' },
    { title: 'Bioinformatics Scientist', label: 'Good Fit' },
    { title: 'Electrician', label: 'Irrelevant' },
    { title: 'Virtual Reality Engineer', label: 'Good Fit' },
    { title: 'Waiter', label: 'Irrelevant' },
    { title: 'SEO Specialist', label: 'Good Fit' },
    { title: 'Janitor', label: 'Irrelevant' },
    { title: 'Natural Language Processing Engineer', label: 'Good Fit' },
    { title: 'Personal Trainer', label: 'Irrelevant' },
    { title: 'IT Project Coordinator', label: 'Good Fit' },
    { title: 'Photographer', label: 'Irrelevant' },
    { title: 'Data Engineer', label: 'Good Fit' },
    { title: 'Chef', label: 'Irrelevant' },
    { title: 'Software Tester', label: 'Good Fit' },
    { title: 'Nurse', label: 'Irrelevant' },
    { title: 'Information Security Analyst', label: 'Good Fit' },
    { title: 'Barista', label: 'Irrelevant' },
    { title: 'UX/UI Designer', label: 'Good Fit' },
    { title: 'Receptionist', label: 'Irrelevant' },
    { title: 'Technical Support Engineer', label: 'Good Fit' },
    { title: 'Hairdresser', label: 'Irrelevant' },
    { title: 'Bioengineer', label: 'Good Fit' },
    { title: 'Driver', label: 'Irrelevant' },
    { title: 'Software Development Manager', label: 'Good Fit' },
    { title: 'Librarian', label: 'Irrelevant' },
    { title: 'Cloud Engineer', label: 'Good Fit' },
    { title: 'Security Guard', label: 'Irrelevant' },
    { title: 'Data Analyst', label: 'Good Fit' },
    { title: 'Gardener', label: 'Irrelevant' },
    { title: 'Mobile Developer', label: 'Good Fit' },
    { title: 'Sales Associate', label: 'Irrelevant' },
    { title: 'AI Engineer', label: 'Good Fit' },
    { title: 'Flight Attendant', label: 'Irrelevant' },
    { title: 'Technical Recruiter', label: 'Good Fit' },
    { title: 'Receptionist', label: 'Irrelevant' },
    { title: 'Software Engineer', label: 'Good Fit' },
    { title: 'Cashier', label: 'Irrelevant' },
    { title: 'Network Architect', label: 'Good Fit' },
    { title: 'Painter', label: 'Irrelevant' },
    { title: 'Site Reliability Engineer', label: 'Good Fit' },
    { title: 'Tutor', label: 'Irrelevant' },
    { title: 'Data Architect', label: 'Good Fit' },
    { title: 'Mechanic', label: 'Irrelevant' },
    { title: 'Machine Learning Specialist', label: 'Good Fit' },
    { title: 'Bartender', label: 'Irrelevant' },
    { title: 'DevSecOps Engineer', label: 'Good Fit' },
    { title: 'Cashier', label: 'Irrelevant' },
    { title: 'SRE Engineer', label: 'Good Fit' },
    { title: 'Florist', label: 'Irrelevant' },
    { title: 'Software Development Engineer in Test', label: 'Good Fit' },
    { title: 'Waiter', label: 'Irrelevant' },
    { title: 'Full Stack Developer', label: 'Good Fit' },
    { title: 'Barista', label: 'Irrelevant' },
    { title: 'Information Technology Manager', label: 'Good Fit' },
    { title: 'Chef', label: 'Irrelevant' },
    { title: 'Data Visualization Specialist', label: 'Good Fit' },
    { title: 'Security Officer', label: 'Irrelevant' },
    { title: 'Backend Engineer', label: 'Good Fit' },
    { title: 'Housekeeper', label: 'Irrelevant' },
    { title: 'Frontend Engineer', label: 'Good Fit' },
    { title: 'Delivery Driver', label: 'Irrelevant' },
    { title: 'Cloud Solutions Developer', label: 'Good Fit' },
    { title: 'Waitress', label: 'Irrelevant' },
    { title: 'Software Development Intern', label: 'Good Fit' },
    { title: 'Retail Associate', label: 'Irrelevant' },
    { title: 'AI Developer', label: 'Good Fit' },
    { title: 'Parking Attendant', label: 'Irrelevant' },
    { title: 'Solutions Architect', label: 'Good Fit' },
    { title: 'Construction Worker', label: 'Irrelevant' },
    { title: 'Technical Account Manager', label: 'Good Fit' },
    { title: 'Massage Therapist', label: 'Irrelevant' },
    { title: 'AI Specialist', label: 'Good Fit' },
    { title: 'Receptionist', label: 'Irrelevant' },
    { title: 'Backend Systems Developer', label: 'Good Fit' },
    { title: 'Barber', label: 'Irrelevant' },
    { title: 'Machine Learning Engineer', label: 'Good Fit' },
    { title: 'Waitstaff', label: 'Irrelevant' },
    { title: 'Data Operations Analyst', label: 'Good Fit' },
    { title: 'Housekeeper', label: 'Irrelevant' },
    { title: 'Software Quality Assurance Engineer', label: 'Good Fit' },
    { title: 'Customer Service Agent', label: 'Irrelevant' },
    { title: 'Frontend Web Developer', label: 'Good Fit' },
    { title: 'Cashier', label: 'Irrelevant' },
    { title: 'AI Architect', label: 'Good Fit' },
    { title: 'Server', label: 'Irrelevant' },
    { title: 'Data Science Manager', label: 'Good Fit' },
    { title: 'Retail Manager', label: 'Irrelevant' },
    { title: 'Backend Developer', label: 'Good Fit' },
    { title: 'Cleaner', label: 'Irrelevant' },
    { title: 'Full Stack Software Engineer', label: 'Good Fit' },
    { title: 'Waiter', label: 'Irrelevant' },
    { title: 'DevOps Specialist', label: 'Good Fit' },
    { title: 'Hostess', label: 'Irrelevant' },
    { title: 'Data Mining Engineer', label: 'Good Fit' },
    { title: 'Busser', label: 'Irrelevant' },
    { title: 'Cloud Infrastructure Engineer', label: 'Good Fit' },
    { title: 'Dishwasher', label: 'Irrelevant' },
    { title: 'Software Development Lead', label: 'Good Fit' },
    { title: 'Barista', label: 'Irrelevant' },
    { title: 'AI Systems Engineer', label: 'Good Fit' },
    { title: 'Host', label: 'Irrelevant' },
    { title: 'Backend API Developer', label: 'Good Fit' },
    { title: 'Concierge', label: 'Irrelevant' },
    { title: 'Software Solutions Engineer', label: 'Good Fit' },
    { title: 'Waitress', label: 'Irrelevant' },
    { title: 'Java Dev', label: 'Good Fit' },
    { title: 'Java Engineer', label: 'Good Fit' },
    { title: 'Java Programmer', label: 'Good Fit' },
    { title: 'Senior Cook', label: 'Irrelevant' },
    { title: 'Junior Cook', label: 'Irrelevant' },
    { title: 'Lead Cook', label: 'Irrelevant' },
    { title: 'ML Eng', label: 'Good Fit' },
    { title: 'ML Developer', label: 'Good Fit' },
    { title: 'ML Specialist', label: 'Good Fit' },
    { title: 'Full Stack Eng', label: 'Good Fit' },
    { title: 'Full Stack Specialist', label: 'Good Fit' },
    { title: 'Senior Full Stack Engineer', label: 'Good Fit' },
    { title: 'Graphic Creator', label: 'Irrelevant' },
    { title: 'Senior Graphic Designer', label: 'Irrelevant' },
    { title: 'Junior Graphic Designer', label: 'Irrelevant' },
    { title: 'Senior Data Scientist', label: 'Good Fit' },
    { title: 'Junior Data Scientist', label: 'Good Fit' },
    { title: 'Lead Data Scientist', label: 'Good Fit' },
    { title: 'Project Lead', label: 'Irrelevant' },
    { title: 'Project Supervisor', label: 'Irrelevant' }
];
// Example usage
(async () => {
    const clientId = 'client123';
    const inputJobTitle = 'Machine Learning Engineer';

    try {
        const classification = await classifyInputForClient(clientId, inputJobTitle, clientData);
        console.log(`The job title "${inputJobTitle}" is classified as: ${classification.result} and confidence ${classification.confidence}`);
    } catch (error) {
        console.error('Error during classification:', error);
    }
})();
